# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: mixed-line-ending
    -   id: check-shebang-scripts-are-executable
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.19.4
    hooks:
    -   id: pyupgrade
        args: [--py37-plus]
-   repo: https://github.com/psf/black
    rev: 21.6b0
    hooks:
    -   id: black
